spring:
  application:
    name: apexpath


  datasource:
    url: jdbc:postgresql://localhost:5432/apexpath_db
    username: apexpath_user
    password: apexpath_password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

  jpa:
    properties:
      hibernate:
        default_schema: public

jwt:
  secret: chave-secreta-para-jwt
  expiration: 86400000